version: '3.8'
services:
  frontend:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./public:/usr/share/nginx/html
    depends_on: 
      - backend
    networks:
      - app
  backend:
    container_name: admin_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on: 
      - db
    networks:
      - app

  db:
    container_name: admin_db
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306 
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
      - app

networks:
  app: